//! Extension methods for twilight-model types.
//!
//! Every `*Ext` trait here is generated by `#[extend::ext]` which produces
//! both the trait definition and the `impl` block in one shot.
//!
//! Instead of hand-rolled builder structs, we use extension methods on the
//! twilight types directly. This is more discoverable, avoids duplicating
//! types, and works naturally with the existing twilight ecosystem.
//!
//! Import everything with `use crate::discord_types::ext::*;` or via the
//! module re-exports in `discord_types/mod.rs`.

use twilight_model::application::command::Command;
use twilight_model::application::command::CommandOption;
use twilight_model::application::command::CommandOptionChoice;
use twilight_model::application::command::CommandOptionType;
use twilight_model::application::command::CommandType;
use twilight_model::channel::message::component::ActionRow;
use twilight_model::channel::message::component::Button;
use twilight_model::channel::message::component::ButtonStyle;
use twilight_model::channel::message::component::Component;
use twilight_model::channel::message::component::SelectMenu;
use twilight_model::channel::message::component::SelectMenuOption;
use twilight_model::channel::message::component::SelectMenuType;
use twilight_model::channel::message::component::TextInput;
use twilight_model::channel::message::component::TextInputStyle;
use twilight_model::channel::message::embed::Embed;
use twilight_model::channel::message::embed::EmbedAuthor;
use twilight_model::channel::message::embed::EmbedField;
use twilight_model::channel::message::embed::EmbedFooter;
use twilight_model::channel::message::embed::EmbedImage;
use twilight_model::channel::message::embed::EmbedThumbnail;
use twilight_model::channel::message::MessageFlags;
use twilight_model::guild::Guild;
use twilight_model::http::interaction::InteractionResponse;
use twilight_model::http::interaction::InteractionResponseData;
use twilight_model::http::interaction::InteractionResponseType;
use twilight_model::id::marker::CommandMarker;
use twilight_model::id::marker::UserMarker;
use twilight_model::id::Id;
use twilight_model::user::CurrentUser;
use twilight_model::user::User;
use twilight_model::util::ImageHash;

// ===========================================================================
// CurrentUserExt  (the bot's own user object, returned in READY)
// ===========================================================================

#[extend::ext(pub, name = CurrentUserExt)]
impl CurrentUser {
	/// Returns the CDN URL for the current user's avatar, or `None` if unset.
	fn avatar_url(&self) -> Option<String> {
		let hash: &ImageHash = self.avatar.as_ref()?;
		Some(format!(
			"https://cdn.discordapp.com/avatars/{}/{}.png",
			self.id, hash
		))
	}

	/// `Username#Discriminator`, or just `Username` for the new username system.
	fn tag(&self) -> String {
		if self.discriminator == 0 {
			self.name.clone()
		} else {
			format!("{}#{:04}", self.name, self.discriminator)
		}
	}
}

// ===========================================================================
// UserExt
// ===========================================================================

#[extend::ext(pub, name = UserExt)]
impl User {
	/// Returns the CDN URL for the user's avatar, or `None` if no avatar is set.
	fn avatar_url(&self) -> Option<String> {
		let hash: &ImageHash = self.avatar.as_ref()?;
		Some(format!(
			"https://cdn.discordapp.com/avatars/{}/{}.png",
			self.id, hash
		))
	}

	/// `Username#Discriminator`, or just `Username` for the new username system.
	fn tag(&self) -> String {
		if self.discriminator == 0 {
			self.name.clone()
		} else {
			format!("{}#{:04}", self.name, self.discriminator)
		}
	}
}

// ===========================================================================
// MessageExt
// ===========================================================================

#[extend::ext(pub, name = MessageExt)]
impl twilight_model::channel::message::Message {
	/// Unix-millisecond timestamp derived from the message snowflake.
	fn snowflake_timestamp_ms(&self) -> Option<u64> {
		let sf = self.id.get();
		// Right-shift by 22 to extract the timestamp portion, then add Discord epoch.
		Some((sf >> 22) + 1_420_070_400_000)
	}

	/// Whether a given user ID is mentioned in the message.
	fn mentions_user(&self, user_id: Id<UserMarker>) -> bool {
		self.mentions.iter().any(|m| m.id == user_id)
	}
}

// ===========================================================================
// GuildExt
// ===========================================================================

#[extend::ext(pub, name = GuildExt)]
impl Guild {
	/// Unix-millisecond timestamp derived from the guild snowflake.
	fn created_at_ms(&self) -> Option<u64> {
		let sf = self.id.get();
		Some((sf >> 22) + 1_420_070_400_000)
	}
}

// ===========================================================================
// IdExt — convenience on Id<T>
// ===========================================================================

#[extend::ext(pub, name = IdExt)]
impl<T> Id<T> {
	/// Get the inner `u64` value of the ID.
	///
	/// Mirrors the old `Snowflake::value()` usage pattern. Note that `Id<T>`
	/// already implements `Display`, so `id.to_string()` also works.
	fn value(&self) -> u64 { self.get() }
}

// ===========================================================================
// CommandExt — replaces ApplicationCommandBuilder
// ===========================================================================

#[extend::ext(pub, name = CommandExt)]
impl Command {
	/// Create a CHAT_INPUT (slash) command.
	#[allow(deprecated)]
	fn chat_input(
		name: impl Into<String>,
		description: impl Into<String>,
	) -> Self {
		Command {
			application_id: None,
			contexts: None,
			default_member_permissions: None,
			dm_permission: None,
			description: description.into(),
			description_localizations: None,
			guild_id: None,
			id: None,
			integration_types: None,
			kind: CommandType::ChatInput,
			name: name.into(),
			name_localizations: None,
			nsfw: None,
			options: Vec::new(),
			version: Id::new(1),
		}
	}

	/// Create a USER context-menu command.
	#[allow(dead_code)]
	#[allow(deprecated)]
	fn user_command(name: impl Into<String>) -> Self {
		Command {
			application_id: None,
			contexts: None,
			default_member_permissions: None,
			dm_permission: None,
			description: String::new(),
			description_localizations: None,
			guild_id: None,
			id: None,
			integration_types: None,
			kind: CommandType::User,
			name: name.into(),
			name_localizations: None,
			nsfw: None,
			options: Vec::new(),
			version: Id::new(1),
		}
	}

	/// Create a MESSAGE context-menu command.
	#[allow(dead_code)]
	#[allow(deprecated)]
	fn message_command(name: impl Into<String>) -> Self {
		Command {
			application_id: None,
			contexts: None,
			default_member_permissions: None,
			dm_permission: None,
			description: String::new(),
			description_localizations: None,
			guild_id: None,
			id: None,
			integration_types: None,
			kind: CommandType::Message,
			name: name.into(),
			name_localizations: None,
			nsfw: None,
			options: Vec::new(),
			version: Id::new(1),
		}
	}

	/// Set the command ID (normally assigned by Discord, not needed for registration).
	#[allow(dead_code)]
	fn with_id(mut self, id: Id<CommandMarker>) -> Self {
		self.id = Some(id);
		self
	}

	/// Add an option to the command.
	fn with_option(mut self, option: CommandOption) -> Self {
		self.options.push(option);
		self
	}

	/// Add a simple option with just a name, description, type, and required flag.
	fn with_simple_option(
		mut self,
		kind: CommandOptionType,
		name: impl Into<String>,
		description: impl Into<String>,
		required: bool,
	) -> Self {
		self.options.push(CommandOption {
			autocomplete: None,
			channel_types: None,
			choices: None,
			description: description.into(),
			description_localizations: None,
			kind,
			max_length: None,
			max_value: None,
			min_length: None,
			min_value: None,
			name: name.into(),
			name_localizations: None,
			options: None,
			required: Some(required),
		});
		self
	}

	/// Mark the command as NSFW.
	#[allow(dead_code)]
	fn with_nsfw(mut self, nsfw: bool) -> Self {
		self.nsfw = Some(nsfw);
		self
	}
}

/// Convenience: build a [`CommandOption`] with choices.
#[allow(dead_code)]
pub fn command_option_with_choices(
	kind: CommandOptionType,
	name: impl Into<String>,
	description: impl Into<String>,
	required: bool,
	choices: Vec<CommandOptionChoice>,
) -> CommandOption {
	CommandOption {
		autocomplete: None,
		channel_types: None,
		choices: Some(choices),
		description: description.into(),
		description_localizations: None,
		kind,
		max_length: None,
		max_value: None,
		min_length: None,
		min_value: None,
		name: name.into(),
		name_localizations: None,
		options: None,
		required: Some(required),
	}
}

// ===========================================================================
// EmbedExt — replaces EmbedBuilder
// ===========================================================================

#[extend::ext(pub, name = EmbedExt)]
impl Embed {
	/// Create a new empty embed.
	fn new() -> Self {
		Embed {
			author: None,
			color: None,
			description: None,
			fields: Vec::new(),
			footer: None,
			image: None,
			kind: String::new(),
			provider: None,
			thumbnail: None,
			timestamp: None,
			title: None,
			url: None,
			video: None,
		}
	}

	/// Set the embed title.
	fn with_title(mut self, title: impl Into<String>) -> Self {
		self.title = Some(title.into());
		self
	}

	/// Set the embed description.
	fn with_description(mut self, desc: impl Into<String>) -> Self {
		self.description = Some(desc.into());
		self
	}

	/// Set the embed color (as a 24-bit RGB integer, e.g. `0xFF6600`).
	fn with_color(mut self, color: u32) -> Self {
		self.color = Some(color);
		self
	}

	/// Add a field to the embed.
	#[allow(dead_code)]
	fn with_field(
		mut self,
		name: impl Into<String>,
		value: impl Into<String>,
		inline: bool,
	) -> Self {
		self.fields.push(EmbedField {
			inline,
			name: name.into(),
			value: value.into(),
		});
		self
	}

	/// Set the footer text.
	fn with_footer(mut self, text: impl Into<String>) -> Self {
		self.footer = Some(EmbedFooter {
			icon_url: None,
			proxy_icon_url: None,
			text: text.into(),
		});
		self
	}

	/// Set the footer text and icon URL.
	#[allow(dead_code)]
	fn with_footer_icon(
		mut self,
		text: impl Into<String>,
		icon_url: impl Into<String>,
	) -> Self {
		self.footer = Some(EmbedFooter {
			icon_url: Some(icon_url.into()),
			proxy_icon_url: None,
			text: text.into(),
		});
		self
	}

	/// Set the thumbnail URL.
	#[allow(dead_code)]
	fn with_thumbnail(mut self, url: impl Into<String>) -> Self {
		self.thumbnail = Some(EmbedThumbnail {
			height: None,
			proxy_url: None,
			url: url.into(),
			width: None,
		});
		self
	}

	/// Set the image URL.
	#[allow(dead_code)]
	fn with_image(mut self, url: impl Into<String>) -> Self {
		self.image = Some(EmbedImage {
			height: None,
			proxy_url: None,
			url: url.into(),
			width: None,
		});
		self
	}

	/// Set the embed author name.
	#[allow(dead_code)]
	fn with_author(mut self, name: impl Into<String>) -> Self {
		self.author = Some(EmbedAuthor {
			icon_url: None,
			name: name.into(),
			proxy_icon_url: None,
			url: None,
		});
		self
	}

	/// Set the embed timestamp (ISO 8601 string).
	///
	/// Uses twilight-model's `Timestamp` which is backed by the `time` crate.
	fn with_timestamp(mut self, ts: impl Into<String>) -> Self {
		if let Ok(parsed) = twilight_model::util::Timestamp::parse(&ts.into()) {
			self.timestamp = Some(parsed);
		}
		self
	}

	/// Set the embed URL.
	#[allow(dead_code)]
	fn with_url(mut self, url: impl Into<String>) -> Self {
		self.url = Some(url.into());
		self
	}
}

// ===========================================================================
// InteractionResponseExt — replaces custom InteractionResponse types
// ===========================================================================

#[extend::ext(pub, name = InteractionResponseExt)]
impl InteractionResponse {
	/// Create a simple text response to an interaction.
	fn text(text: impl Into<String>) -> Self {
		InteractionResponse {
			kind: InteractionResponseType::ChannelMessageWithSource,
			data: Some(InteractionResponseData {
				content: Some(text.into()),
				..Default::default()
			}),
		}
	}

	/// Create a Pong response (for interaction ping).
	fn pong() -> Self {
		InteractionResponse {
			kind: InteractionResponseType::Pong,
			data: None,
		}
	}

	/// Create a deferred response (shows a loading state).
	fn defer() -> Self {
		InteractionResponse {
			kind: InteractionResponseType::DeferredChannelMessageWithSource,
			data: None,
		}
	}

	/// Create a message response with full data.
	fn message(data: InteractionResponseData) -> Self {
		InteractionResponse {
			kind: InteractionResponseType::ChannelMessageWithSource,
			data: Some(data),
		}
	}

	/// Create an update-message response (for component interactions).
	fn update(data: InteractionResponseData) -> Self {
		InteractionResponse {
			kind: InteractionResponseType::UpdateMessage,
			data: Some(data),
		}
	}

	/// Create a modal response.
	fn modal(data: InteractionResponseData) -> Self {
		InteractionResponse {
			kind: InteractionResponseType::Modal,
			data: Some(data),
		}
	}
}

#[extend::ext(pub, name = InteractionResponseDataExt)]
impl InteractionResponseData {
	/// Set the text content.
	fn with_content(mut self, content: impl Into<String>) -> Self {
		self.content = Some(content.into());
		self
	}

	/// Set the embeds.
	fn with_embeds(mut self, embeds: Vec<Embed>) -> Self {
		self.embeds = Some(embeds);
		self
	}

	/// Set the components.
	fn with_components(mut self, components: Vec<Component>) -> Self {
		self.components = Some(components);
		self
	}

	/// Set the flags (e.g. `MessageFlags::EPHEMERAL`).
	fn with_flags(mut self, flags: MessageFlags) -> Self {
		self.flags = Some(flags);
		self
	}

	/// Set the title (for modals).
	fn with_title(mut self, title: impl Into<String>) -> Self {
		self.title = Some(title.into());
		self
	}

	/// Set the custom_id (for modals).
	fn with_custom_id(mut self, custom_id: impl Into<String>) -> Self {
		self.custom_id = Some(custom_id.into());
		self
	}
}

// ===========================================================================
// Component helper functions
// ===========================================================================

/// Build an Action Row wrapping other components.
pub fn action_row(components: Vec<Component>) -> Component {
	Component::ActionRow(ActionRow {
		components,
		id: None,
	})
}

/// Build a button component.
///
/// `style` values: 1=Primary, 2=Secondary, 3=Success, 4=Danger.
/// For link buttons (style 5), use [`link_button`] instead.
pub fn button(
	style: u8,
	label: impl Into<String>,
	custom_id: impl Into<String>,
) -> Component {
	let button_style = match style {
		1 => ButtonStyle::Primary,
		2 => ButtonStyle::Secondary,
		3 => ButtonStyle::Success,
		4 => ButtonStyle::Danger,
		_ => ButtonStyle::Primary,
	};

	Component::Button(Button {
		custom_id: Some(custom_id.into()),
		disabled: false,
		emoji: None,
		label: Some(label.into()),
		style: button_style,
		url: None,
		sku_id: None,
		id: None,
	})
}

/// Build a link button (style 5, no custom_id, requires url).
#[allow(dead_code)]
pub fn link_button(
	label: impl Into<String>,
	url: impl Into<String>,
) -> Component {
	Component::Button(Button {
		custom_id: None,
		disabled: false,
		emoji: None,
		label: Some(label.into()),
		style: ButtonStyle::Link,
		url: Some(url.into()),
		sku_id: None,
		id: None,
	})
}

/// Build a string select menu component.
#[allow(dead_code)]
pub fn string_select(
	custom_id: impl Into<String>,
	placeholder: impl Into<String>,
	options: Vec<SelectMenuOption>,
) -> Component {
	Component::SelectMenu(SelectMenu {
		channel_types: None,
		custom_id: custom_id.into(),
		default_values: None,
		disabled: false,
		kind: SelectMenuType::Text,
		max_values: Some(1),
		min_values: Some(1),
		options: Some(options),
		placeholder: Some(placeholder.into()),
		id: None,
		required: None,
	})
}

/// Build a text input for use inside a modal.
///
/// `style`: 1 = Short, 2 = Paragraph.
pub fn text_input(
	custom_id: impl Into<String>,
	label: impl Into<String>,
	style: u8,
	required: bool,
) -> Component {
	let input_style = match style {
		1 => TextInputStyle::Short,
		2 => TextInputStyle::Paragraph,
		_ => TextInputStyle::Short,
	};

	#[allow(deprecated)]
	Component::TextInput(TextInput {
		custom_id: custom_id.into(),
		label: Some(label.into()),
		max_length: None,
		min_length: None,
		placeholder: None,
		required: Some(required),
		style: input_style,
		value: None,
		id: None,
	})
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
	use super::*;
	use twilight_model::id::marker::GuildMarker;
	use twilight_model::id::marker::MessageMarker;

	fn make_test_user() -> User {
		serde_json::from_value(serde_json::json!({
			"id": "789",
			"username": "alice",
			"discriminator": "0001",
			"avatar": null,
			"bot": false,
		}))
		.expect("valid user JSON")
	}

	#[test]
	fn user_tag_with_discriminator() {
		let user: User = serde_json::from_value(serde_json::json!({
			"id": "789",
			"username": "alice",
			"discriminator": "0001",
			"avatar": null,
		}))
		.unwrap();

		assert_eq!(user.tag(), "alice#0001");
	}

	#[test]
	fn user_tag_new_system() {
		let user: User = serde_json::from_value(serde_json::json!({
			"id": "789",
			"username": "alice",
			"discriminator": "0",
			"avatar": null,
		}))
		.unwrap();

		assert_eq!(user.tag(), "alice");
	}

	#[test]
	fn user_avatar_url_none_when_no_avatar() {
		let user = make_test_user();
		assert!(user.avatar_url().is_none());
	}

	#[test]
	fn user_avatar_url_present() {
		let user: User = serde_json::from_value(serde_json::json!({
			"id": "789",
			"username": "alice",
			"discriminator": "0",
			"avatar": "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d",
		}))
		.unwrap();

		let url = user.avatar_url().unwrap();
		assert!(url.contains("789"));
		assert!(url.starts_with("https://cdn.discordapp.com/avatars/"));
	}

	#[test]
	fn guild_created_at_ms() {
		let guild_id = Id::<GuildMarker>::new(175928847299117063);
		let expected = (175928847299117063u64 >> 22) + 1_420_070_400_000;
		let sf = guild_id.get();
		let ms = (sf >> 22) + 1_420_070_400_000;
		assert_eq!(ms, expected);
	}

	#[test]
	fn message_snowflake_timestamp() {
		let msg_id = Id::<MessageMarker>::new(175928847299117063);
		let expected = (175928847299117063u64 >> 22) + 1_420_070_400_000;
		let sf = msg_id.get();
		let ms = (sf >> 22) + 1_420_070_400_000;
		assert_eq!(ms, expected);
	}

	#[test]
	fn id_ext_value() {
		let id = Id::<GuildMarker>::new(12345);
		assert_eq!(id.value(), 12345);
	}

	#[test]
	fn current_user_tag_with_discriminator() {
		let user: CurrentUser = serde_json::from_value(serde_json::json!({
			"id": "1",
			"username": "bot",
			"discriminator": "0042",
			"avatar": null,
			"bot": true,
			"mfa_enabled": false,
			"verified": true,
		}))
		.unwrap();
		assert_eq!(user.tag(), "bot#0042");
	}

	#[test]
	fn current_user_tag_new_system() {
		let user: CurrentUser = serde_json::from_value(serde_json::json!({
			"id": "1",
			"username": "coolbot",
			"discriminator": "0",
			"avatar": null,
			"bot": true,
			"mfa_enabled": false,
			"verified": true,
		}))
		.unwrap();
		assert_eq!(user.tag(), "coolbot");
	}

	#[test]
	fn current_user_avatar_url_none_when_no_avatar() {
		let user: CurrentUser = serde_json::from_value(serde_json::json!({
			"id": "1",
			"username": "bot",
			"discriminator": "0",
			"avatar": null,
			"bot": true,
			"mfa_enabled": false,
			"verified": true,
		}))
		.unwrap();
		assert!(user.avatar_url().is_none());
	}

	// -- CommandExt ---------------------------------------------------------

	#[test]
	fn command_ext_chat_input() {
		let cmd = Command::chat_input("ping", "Check bot latency");
		assert_eq!(cmd.name, "ping");
		assert_eq!(cmd.description, "Check bot latency");
		assert!(matches!(cmd.kind, CommandType::ChatInput));
		assert!(cmd.options.is_empty());
	}

	#[test]
	fn command_ext_with_option() {
		let cmd = Command::chat_input("roll", "Roll a dice")
			.with_simple_option(
				CommandOptionType::Integer,
				"sides",
				"Number of sides",
				false,
			);

		assert_eq!(cmd.options.len(), 1);
		assert_eq!(cmd.options[0].name, "sides");
		assert!(matches!(cmd.options[0].kind, CommandOptionType::Integer));
		assert_eq!(cmd.options[0].required, Some(false));
	}

	// -- EmbedExt -----------------------------------------------------------

	#[test]
	fn embed_ext_basic() {
		let embed = Embed::new()
			.with_title("Test Title")
			.with_description("Test Description")
			.with_color(0xFF0000)
			.with_footer("Footer text");

		assert_eq!(embed.title.as_deref(), Some("Test Title"));
		assert_eq!(embed.description.as_deref(), Some("Test Description"));
		assert_eq!(embed.color, Some(0xFF0000));
		assert!(embed.footer.is_some());
		assert_eq!(embed.footer.unwrap().text, "Footer text");
	}

	#[test]
	fn embed_ext_with_fields() {
		let embed = Embed::new()
			.with_field("Name1", "Value1", true)
			.with_field("Name2", "Value2", false);

		assert_eq!(embed.fields.len(), 2);
		assert_eq!(embed.fields[0].name, "Name1");
		assert!(embed.fields[0].inline);
		assert_eq!(embed.fields[1].name, "Name2");
		assert!(!embed.fields[1].inline);
	}

	// -- InteractionResponseExt ---------------------------------------------

	#[test]
	fn interaction_response_text() {
		let resp = InteractionResponse::text("hello");
		assert!(matches!(
			resp.kind,
			InteractionResponseType::ChannelMessageWithSource
		));
		assert_eq!(
			resp.data.as_ref().unwrap().content.as_deref(),
			Some("hello")
		);
	}

	#[test]
	fn interaction_response_pong() {
		let resp = InteractionResponse::pong();
		assert!(matches!(resp.kind, InteractionResponseType::Pong));
		assert!(resp.data.is_none());
	}

	#[test]
	fn interaction_response_defer() {
		let resp = InteractionResponse::defer();
		assert!(matches!(
			resp.kind,
			InteractionResponseType::DeferredChannelMessageWithSource
		));
	}

	#[test]
	fn interaction_response_data_ext() {
		let data = InteractionResponseData::default()
			.with_content("hi")
			.with_flags(MessageFlags::EPHEMERAL);

		assert_eq!(data.content.as_deref(), Some("hi"));
		assert_eq!(data.flags, Some(MessageFlags::EPHEMERAL));
	}

	// -- Component helpers --------------------------------------------------

	#[test]
	fn action_row_wraps_components() {
		let row = action_row(vec![button(1, "Click", "btn_click")]);
		match row {
			Component::ActionRow(ar) => assert_eq!(ar.components.len(), 1),
			_ => panic!("expected ActionRow"),
		}
	}

	#[test]
	fn button_creates_correct_component() {
		let btn = button(3, "OK", "btn_ok");
		match btn {
			Component::Button(b) => {
				assert_eq!(b.label.as_deref(), Some("OK"));
				assert_eq!(b.custom_id.as_deref(), Some("btn_ok"));
				assert!(matches!(b.style, ButtonStyle::Success));
			}
			_ => panic!("expected Button"),
		}
	}

	#[test]
	fn link_button_has_url_and_no_custom_id() {
		let btn = link_button("Visit", "https://example.com");
		match btn {
			Component::Button(b) => {
				assert!(b.custom_id.is_none());
				assert_eq!(b.url.as_deref(), Some("https://example.com"));
				assert!(matches!(b.style, ButtonStyle::Link));
			}
			_ => panic!("expected Button"),
		}
	}

	#[test]
	fn text_input_creates_correct_component() {
		let ti = text_input("my_input", "Enter text", 2, true);
		match ti {
			Component::TextInput(t) => {
				assert_eq!(t.custom_id, "my_input");
				assert!(matches!(t.style, TextInputStyle::Paragraph));
				assert_eq!(t.required, Some(true));
			}
			_ => panic!("expected TextInput"),
		}
	}
}
